spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS   #控制台彩色打印输出
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - httptrace
          - threaddump
operation-log:
  applicationName: testApplication
  storageType: LOCAL_MONGODB
server:
  servlet:
    context-path: /operationlog-producer-rest
  port: 80